<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315125858 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE boards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F3EE4D13166D1F9C ON boards (project_id)');
        $this->addSql('CREATE TABLE cards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, priority VARCHAR(255) DEFAULT \'medium\' NOT NULL, due_date DATE DEFAULT NULL, position INT NOT NULL, column_id INT NOT NULL, assignee_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C258FDBE8E8ED5 ON cards (column_id)');
        $this->addSql('CREATE INDEX IDX_4C258FD59EC7D60 ON cards (assignee_id)');
        $this->addSql('CREATE TABLE card_labels (card_id INT NOT NULL, label_id INT NOT NULL, PRIMARY KEY (card_id, label_id))');
        $this->addSql('CREATE INDEX IDX_C7EE51654ACC9A20 ON card_labels (card_id)');
        $this->addSql('CREATE INDEX IDX_C7EE516533B92F39 ON card_labels (label_id)');
        $this->addSql('CREATE TABLE columns (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, color VARCHAR(32) DEFAULT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ACCEC0B7E7EC5785 ON columns (board_id)');
        $this->addSql('CREATE TABLE labels (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(32) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, read BOOLEAN DEFAULT false NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE INDEX IDX_6000B0D34ACC9A20 ON notifications (card_id)');
        $this->addSql('CREATE TABLE project_members (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(255) DEFAULT \'member\' NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3BEDE9A166D1F9C ON project_members (project_id)');
        $this->addSql('CREATE INDEX IDX_D3BEDE9AA76ED395 ON project_members (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_project_member ON project_members (project_id, user_id)');
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, color VARCHAR(32) DEFAULT NULL, archived BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C93B3A47E3C61F9 ON projects (owner_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, global_role VARCHAR(255) DEFAULT \'member\' NOT NULL, avatar_url TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE boards ADD CONSTRAINT FK_F3EE4D13166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_4C258FDBE8E8ED5 FOREIGN KEY (column_id) REFERENCES columns (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_4C258FD59EC7D60 FOREIGN KEY (assignee_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_labels ADD CONSTRAINT FK_C7EE51654ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_labels ADD CONSTRAINT FK_C7EE516533B92F39 FOREIGN KEY (label_id) REFERENCES labels (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE columns ADD CONSTRAINT FK_ACCEC0B7E7EC5785 FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D34ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_members ADD CONSTRAINT FK_D3BEDE9A166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_members ADD CONSTRAINT FK_D3BEDE9AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A47E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE boards DROP CONSTRAINT FK_F3EE4D13166D1F9C');
        $this->addSql('ALTER TABLE cards DROP CONSTRAINT FK_4C258FDBE8E8ED5');
        $this->addSql('ALTER TABLE cards DROP CONSTRAINT FK_4C258FD59EC7D60');
        $this->addSql('ALTER TABLE card_labels DROP CONSTRAINT FK_C7EE51654ACC9A20');
        $this->addSql('ALTER TABLE card_labels DROP CONSTRAINT FK_C7EE516533B92F39');
        $this->addSql('ALTER TABLE columns DROP CONSTRAINT FK_ACCEC0B7E7EC5785');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D34ACC9A20');
        $this->addSql('ALTER TABLE project_members DROP CONSTRAINT FK_D3BEDE9A166D1F9C');
        $this->addSql('ALTER TABLE project_members DROP CONSTRAINT FK_D3BEDE9AA76ED395');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A47E3C61F9');
        $this->addSql('DROP TABLE boards');
        $this->addSql('DROP TABLE cards');
        $this->addSql('DROP TABLE card_labels');
        $this->addSql('DROP TABLE columns');
        $this->addSql('DROP TABLE labels');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE project_members');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
