<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260516113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add TOTP two-factor authentication fields and login challenges';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD totp_secret VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD totp_pending_secret VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE TABLE login_two_factor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, attempts INT NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C5F11DDBA76ED395 ON login_two_factor (user_id)');
        $this->addSql('CREATE INDEX idx_2fa_challenge_token_hash ON login_two_factor (token_hash)');
        $this->addSql('CREATE INDEX idx_2fa_challenge_expires_at ON login_two_factor (expires_at)');
        $this->addSql('ALTER TABLE login_two_factor ADD CONSTRAINT FK_C5F11DDBA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE login_two_factor DROP CONSTRAINT FK_C5F11DDBA76ED395');
        $this->addSql('DROP TABLE login_two_factor');
        $this->addSql('ALTER TABLE users DROP totp_secret');
        $this->addSql('ALTER TABLE users DROP totp_pending_secret');
    }
}
