<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260509190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add comments to cards.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE card_comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, card_id INT NOT NULL, author_id INT DEFAULT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FDBE5B4A4ACC9A20 ON card_comments (card_id)');
        $this->addSql('CREATE INDEX IDX_FDBE5B4AF675F31B ON card_comments (author_id)');
        $this->addSql('CREATE INDEX idx_card_comment_card_created ON card_comments (card_id, created_at)');
        $this->addSql('ALTER TABLE card_comments ADD CONSTRAINT FK_FDBE5B4A4ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_comments ADD CONSTRAINT FK_FDBE5B4AF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE card_comments DROP CONSTRAINT FK_FDBE5B4A4ACC9A20');
        $this->addSql('ALTER TABLE card_comments DROP CONSTRAINT FK_FDBE5B4AF675F31B');
        $this->addSql('DROP TABLE card_comments');
    }
}
