<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260506123521 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, description TEXT NOT NULL, details JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C91E0E44166D1F9C ON project_logs (project_id)');
        $this->addSql('CREATE INDEX IDX_C91E0E44A76ED395 ON project_logs (user_id)');
        $this->addSql('ALTER TABLE project_logs ADD CONSTRAINT FK_C91E0E44166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_logs ADD CONSTRAINT FK_C91E0E44A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_card_assignee_column ON cards (assignee_id, column_id)');
        $this->addSql('CREATE INDEX idx_notification_user_read ON notifications (user_id, read)');
        $this->addSql('CREATE INDEX idx_notification_sent_at ON notifications (sent_at)');
        $this->addSql('CREATE INDEX idx_project_archived ON projects (archived)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rememberme_token (series VARCHAR(88) NOT NULL, value VARCHAR(88) NOT NULL, lastused TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, class VARCHAR(100) DEFAULT \'\' NOT NULL, username VARCHAR(200) NOT NULL, PRIMARY KEY (series))');
        $this->addSql('ALTER TABLE project_logs DROP CONSTRAINT FK_C91E0E44166D1F9C');
        $this->addSql('ALTER TABLE project_logs DROP CONSTRAINT FK_C91E0E44A76ED395');
        $this->addSql('DROP TABLE project_logs');
        $this->addSql('DROP INDEX idx_card_assignee_column');
        $this->addSql('DROP INDEX idx_notification_user_read');
        $this->addSql('DROP INDEX idx_notification_sent_at');
        $this->addSql('DROP INDEX idx_project_archived');
    }
}
